name: single job docker deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: java-github-actions-demo

    steps:
      - uses: actions/checkout@v4
      - run: mvn package
     
